export enum PedType {
    Player1 = 0,
    Player2 = 1,
    Player3 = 2,
    Player4 = 3,
    CivMale = 4,
    CivFemale = 5,
    Cop = 6,
    Gang1 = 7,
    Gang2 = 8,
    Gang3 = 9,
    Gang4 = 10,
    Gang5 = 11,
    Gang6 = 12,
    Gang7 = 13,
    Gang8 = 14,
    Gang9 = 15,
    Emergency = 16,
    Fireman = 17,
    Criminal = 18,
    Prostitute = 20,
    Special = 21,
}
export enum Fade {
    Out = 0,
    In = 1,
    None = 2,
}
export enum WeaponType {
    Unarmed = 0,
    BrassKnuckles = 1,
    Screwdriver = 2,
    GolfClub = 3,
    NightStick = 4,
    Knife = 5,
    BaseballBat = 6,
    Hammer = 7,
    Cleaver = 8,
    Machete = 9,
    Katana = 10,
    Chainsaw = 11,
    Grenade = 12,
    DetonatorGrenade = 13,
    Teargas = 14,
    Molotov = 15,
    Rocket = 16,
    Pistol = 17,
    Python = 18,
    Shotgun = 19,
    Spas12 = 20,
    Stubby = 21,
    Tec9 = 22,
    Uzi = 23,
    SilencedIngram = 24,
    Mp5 = 25,
    M4 = 26,
    Ruger = 27,
    Sniper = 28,
    Laserscope = 29,
    RocketLauncher = 30,
    Flamethrower = 31,
    M60 = 32,
    Minigun = 33,
    Detonator = 34,
    Helicannon = 35,
    Camera = 36,
    Health = 37,
    Armour = 38,
    RammedByCar = 39,
    RunOverByCar = 40,
    Explosion = 41,
    UziDriveby = 42,
    Drowning = 43,
    Fall = 44,
    Unidentified = 45,
    AnyMelee = 46,
    AnyWeapon = 47,
}
export enum Button {
    LeftStickX = 0,
    LeftStickY = 1,
    RightStickX = 2,
    RightStickY = 3,
    LeftShoulder1 = 4,
    LeftShoulder2 = 5,
    RightShoulder1 = 6,
    RightShoulder2 = 7,
    DpadUp = 8,
    DpadDown = 9,
    DpadLeft = 10,
    DpadRight = 11,
    Start = 12,
    Select = 13,
    Square = 14,
    Triangle = 15,
    Cross = 16,
    Circle = 17,
    LeftShock = 18,
    RightShock = 19,
}
export enum AnimGroup {
    Man = 0,
    Van = 1,
    Coach = 2,
    Bikes = 3,
    Bikev = 4,
    Bikeh = 5,
    Biked = 6,
    Unarmed = 7,
    Screwdrv = 8,
    Knife = 9,
    Baseball = 10,
    Golfclub = 11,
    Chainsaw = 12,
    Python = 13,
    Colt45 = 14,
    Shotgun = 15,
    Buddy = 16,
    Tec = 17,
    Uzi = 18,
    Rifle = 19,
    M60 = 20,
    Sniper = 21,
    Grenade = 22,
    Flame = 23,
    Medic = 24,
    Sunbathe = 25,
    Playidles = 26,
    Riot = 27,
    Strip = 28,
    Lance = 29,
    Player = 30,
    PlayerRocket = 31,
    Player1Armed = 32,
    Player2Armed = 33,
    PlayerBbbat = 34,
    PlayerCsaw = 35,
    Shuffle = 36,
    Oldman = 37,
    Gang1 = 38,
    Gang2 = 39,
    Fatman = 40,
    OldFatman = 41,
    Jogger = 42,
    Woman = 43,
    Shopping = 44,
    BusyWoman = 45,
    SexyWoman = 46,
    FatWoman = 47,
    OldWoman = 48,
    JogWoman = 49,
    PanicChunky = 50,
    Skate = 51,
    PlayerBack = 52,
    PlayerLeft = 53,
    PlayerRight = 54,
    RocketBack = 55,
    RocketLeft = 56,
    RocketRight = 57,
    CsawBack = 58,
    CsawLeft = 59,
    CsawRight = 60,
}
export enum TimerDirection {
    Up = 0,
    Down = 1,
}
export enum TextStyle {
    Middle = 1,
    BottomRight = 2,
    GreenBottomRight = 3,
    MiddleSmaller = 4,
    MiddleSmallerHigher = 5,
    BlueMiddleSmaller = 6,
}
export enum CounterDisplay {
    Number = 0,
    Bar = 1,
}
export enum WeatherType {
    Sunny = 0,
    Cloudy = 1,
    Rainy = 2,
    Foggy = 3,
    ExtraSunny = 4,
    Hurricane = 5,
    ExtraColours = 6,
}
export enum MoveState {
    None = 0,
    Still = 1,
    Walk = 2,
    Jog = 3,
    Run = 4,
    Sprint = 5,
    Thrown = 6,
}
export enum CarMission {
    None = 0,
    Cruise = 1,
    RamPlayerFaraway = 2,
    RamPlayerClose = 3,
    BlockPlayerFaraway = 4,
    BlockPlayerClose = 5,
    BlockPlayerHandbrakeStop = 6,
    WaitForDeletion = 7,
    GotoCoords = 8,
    GotoCoordsStraight = 9,
    EmergencyVehicleStop = 10,
    StopForever = 11,
    GotoCoordsAccurate = 12,
    GotoCoordsStraightAccurate = 13,
    GotoCoordsAsthecrowSwims = 14,
    RamCarFaraway = 15,
    RamCarClose = 16,
    BlockCarFaraway = 17,
    BlockCarClose = 18,
    BlockCarHandbrakeStop = 19,
    HeliFlyToCoors = 20,
    AttackPlayer = 21,
    PlaneFlyToCoors = 22,
    HeliLand = 23,
    SlowlyDriveTowardsPlayer1 = 24,
    SlowlyDriveTowardsPlayer2 = 25,
    BlockPlayerForwardAndBack = 26,
}
export enum FlareType {
    None = 0,
    Sun = 1,
    Headlights = 2,
}
export enum CameraMode {
    None = 0,
    TopDown = 1,
    GTAClassic = 2,
    BehindCar = 3,
    FollowPed = 4,
    Aiming = 5,
    Debug = 6,
    Sniper = 7,
    RocketLauncher = 8,
    ModelView = 9,
    Bill = 10,
    Syphon = 11,
    Circle = 12,
    CheezyZoom = 13,
    WheelCam = 14,
    Fixed = 15,
    FirstPerson = 16,
    Flyby = 17,
    CamOnAString = 18,
    Reaction = 19,
    FollowPedWithBind = 20,
    Chris = 21,
    BehindBoat = 22,
    PlayerFallenWater = 23,
    CamOnTrainRoof = 24,
    CamRunningSideTrain = 25,
    BloodOnTheTracks = 26,
    ImThePassengerWooWoo = 27,
    SyphonCrimInFront = 28,
    PedDeadBaby = 29,
    PillowsPaps = 30,
    LookAtCars = 31,
    ArrestCamOne = 32,
    ArrestCamTwo = 33,
    M16FirstPerson = 34,
    SpecialFixedForSyphon = 35,
    FightCam = 36,
    TopDownPed = 37,
    Lighthouse = 38,
    SniperRunabout = 39,
    RocketLauncherRunabout = 40,
    FirstPersonRunabout = 41,
    M16FirstPersonRunabout = 42,
    FightCamRunabout = 43,
    Editor = 44,
    HelicannonFirstPerson = 45,
    Camera = 46,
}
export enum DayOrNight {
    Night = 0,
    Day = 1,
}
export enum HudObject {
    Armor = 3,
    Health = 4,
    Radar = 8,
}
export enum StuntType {
    NoStunt = 0,
    Insane = 1,
    PerfectInsane = 2,
    DoubleInsane = 3,
    PerfectDoubleInsane = 4,
    TripleInsane = 5,
    PerfectTripleInsane = 6,
    QuadrupleInsane = 7,
    PerfectQuadrupleInsane = 8,
}
export enum ExplosionType {
    Grenade = 0,
    Molotov = 1,
    Rocket = 2,
    Car = 3,
    CarQuick = 4,
    Boat = 5,
    Heli = 6,
    Heli2 = 7,
    Mine = 8,
    Barrel = 9,
    TankGrenade = 10,
    HeliBomb = 11,
}
export enum PedStat {
    Player = 0,
    Cop = 1,
    Medic = 2,
    Fire = 3,
    Gang1 = 4,
    Gang2 = 5,
    Gang3 = 6,
    Gang4 = 7,
    Gang5 = 8,
    Gang6 = 9,
    Gang7 = 10,
    StreetGuy = 11,
    SuitGuy = 12,
    SensibleGuy = 13,
    GeekGuy = 14,
    OldGuy = 15,
    ToughGuy = 16,
    StreetGirl = 17,
    SuitGirl = 18,
    SensibleGirl = 19,
    GeekGirl = 20,
    OldGirl = 21,
    ToughGirl = 22,
    TrampMale = 23,
    TrampFemale = 24,
    Tourist = 25,
    Prostitute = 26,
    Criminal = 27,
    Busker = 28,
    TaxiDriver = 29,
    Psycho = 30,
    Steward = 31,
    Sportsfan = 32,
    Shopper = 33,
    OldShopper = 34,
    BeachGuy = 35,
    BeachGirl = 36,
    Skater = 37,
    StdMission = 38,
    Coward = 39,
}
export enum SwitchType {
    None = 0,
    Interpolation = 1,
    JumpCut = 2,
}
export enum BlipDisplay {
    Neither = 0,
    MarkerOnly = 1,
    BlipOnly = 2,
    Both = 3,
}
export enum ShadowTextureType {
    None = 0,
    Car = 1,
    Ped = 2,
    Explosion = 3,
    Heli = 4,
    Headlights = 5,
    Blood = 6,
    Bike = 7,
    Rcbaron = 8,
}
export enum BlipColor {
    Red = 0,
    Green = 1,
    LightBlue = 2,
    Gray = 3,
    Yellow = 4,
    Magenta = 5,
    Cyan = 6,
}
export enum TempAction {
    None = 0,
    Wait = 1,
    Reverse = 2,
    HandbrakeTurnLeft = 3,
    HandbrakeTurnRight = 4,
    HandbrakeStraight = 5,
    TurnLeft = 6,
    TurnRight = 7,
    GoForward = 8,
    SwerveLeft = 9,
    SwerveRight = 10,
}
export enum CarDoor {
    Hood = 0,
    Trunk = 1,
    LeftFrontDoor = 2,
    RightFrontDoor = 3,
    LeftRearDoor = 4,
    RightRearDoor = 5,
}
export enum GarageType {
    None = 0,
    Mission = 1,
    BombShop1 = 2,
    BombShop2 = 3,
    BombShop3 = 4,
    Respray = 5,
    CollectorsItems = 6,
    CollectSpecificCars = 7,
    CollectCars1 = 8,
    CollectCars2 = 9,
    CollectCars3 = 10,
    ForCarToComeOutOf = 11,
    _60Seconds = 12,
    Crusher = 13,
    MissionKeepCar = 14,
    ForScriptToOpen = 15,
    HideoutOne = 16,
    HideoutTwo = 17,
    HideoutThree = 18,
    ForScriptToOpenAndClose = 19,
    KeepsOpeningForSpecificCar = 20,
    MissionKeepCarRemainClosed = 21,
    CollectCars4 = 22,
    ForScriptToOpenForCar = 23,
    HideoutFour = 24,
    HideoutFive = 25,
    HideoutSix = 26,
    HideoutSeven = 27,
    HideoutEight = 28,
    HideoutNine = 29,
    HideoutTen = 30,
    HideoutEleven = 31,
    HideoutTwelve = 32,
}
export enum ScrollbarMessage {
    Hotring = 0,
    Bloodring = 1,
    Dirtring = 2,
}
export enum SetPieceType {
    None = 0,
    TwoCopCarsInAlley = 1,
    CarBlockingPlayerFromSide = 2,
    CarRammingPlayerFromSide = 3,
    CreateCopperOnFoot = 4,
    CreateTwoCoppersOnFoot = 5,
    TwoCarsBlockingPlayerFromSide = 6,
    TwoCarsRammingPlayerFromSide = 7,
}
export enum MissionAudioSlot {
    Slot1 = 1,
    Slot2 = 2,
}
export enum Clothing {
    Street = 1,
    Soiree = 2,
    Coveralls = 3,
    CountryClub = 4,
    Havana = 5,
    Cop = 6,
    BankJob = 7,
    Casual = 8,
    MrVercetti = 9,
    TrackSuitBlack = 10,
    TrackSuitRed = 11,
    Frankie = 12,
    McTommy = 13,
}
export enum AnnouncementTrack {
    BridgeClosed = 0,
    BridgeOpen = 1,
}
export enum Interior {
    MainMap = 0,
    Hotel = 1,
    Mansion = 2,
    Bank = 3,
    Mall = 4,
    StripClub = 5,
    Lawyers = 6,
    CoffeeShop = 7,
    ConcertHall = 8,
    Studio = 9,
    RifleRange = 10,
    BikerBar = 11,
    PoliceStation = 12,
    Everywhere = 13,
    Dirt = 14,
    Blood = 15,
    Ovalring = 16,
    MalibuClub = 17,
    PrintWorks = 18,
}
export enum ScriptSound {
    SoundBankAlarmLoop = 0,
    SoundPartMissionComplete = 1,
    SoundPoliceCellDoorSlidingLoop = 2,
    SoundPoliceCellDoorClunk = 3,
    SoundGarageDoorSlidingLoop = 4,
    SoundGarageDoorClunk = 5,
    SoundSnoringLoop = 6,
    SoundRaceStart3 = 7,
    SoundRaceStart2 = 8,
    SoundRaceStart1 = 9,
    SoundRaceStartGo = 10,
    SoundShootingRangeTargetMovingLoop = 11,
    SoundShootingRangeTargetHit = 12,
    SoundAmmunationBuyWeapon = 13,
    SoundAmmunationBuyWeaponDenied = 14,
    SoundWmycwTicketSpeech = 15,
    SoundImranArmBomb = 16,
    SoundAndySniperShot = 17,
    SoundWillieCardSwipe = 18,
    SoundMaleAmbulanceOuch = 19,
    SoundFemaleAmbulanceOuch = 20,
    SoundBuildingBar1 = 21,
    SoundBuildingBar2 = 22,
    SoundBuildingBar3 = 23,
    SoundBuildingBar4 = 24,
    SoundBuildingBikerBar = 25,
    SoundBuildingChurch = 26,
    SoundBuildingClub = 27,
    SoundBuildingCuba1 = 28,
    SoundBuildingCuba2 = 29,
    SoundBuildingVoodoo = 30,
    SoundBuildingMusicShop = 31,
    SoundBuildingStripclub1 = 32,
    SoundBuildingStripclub2 = 33,
    SoundBuildingSupersweep = 34,
    SoundSeaplaneLowFuel = 35,
    SoundNewBuildingBar1 = 36,
    SoundNewBuildingBar2 = 37,
    SoundNewBuildingBar3 = 38,
    SoundNewBuildingBar4 = 39,
    SoundNewBuildingMalibu1 = 40,
    SoundNewBuildingMalibu2 = 41,
    SoundNewBuildingMalibu3 = 42,
    SoundNewBuildingStrip1 = 43,
    SoundNewBuildingStrip2 = 44,
    SoundNewBuildingStrip3 = 45,
    SoundNewBuildingChurch = 46,
    SoundNewBuildingFan1 = 47,
    SoundNewBuildingFan2 = 48,
    SoundNewBuildingInsect1 = 49,
    SoundNewBuildingInsect2 = 50,
    SoundNewWaterfall = 51,
    SoundBulletHitGround1 = 52,
    SoundBulletHitGround2 = 53,
    SoundBulletHitGround3 = 54,
    SoundBulletHitWater = 55,
    SoundPayphoneRinging = 56,
    SoundGlassBreakL = 57,
    SoundGlassBreakS = 58,
    SoundGlassCrack = 59,
    SoundGlassLightBreak = 60,
    SoundBoxDestroyed1 = 61,
    SoundBoxDestroyed2 = 62,
    SoundMetalCollision = 63,
    SoundTireCollision = 64,
    SoundHitBall = 65,
    SoundGunshellDrop = 66,
    SoundGunshellDropSoft = 67,
    SoundTotal = 68,
    SoundInvalid = 69,
}
export enum WaitState {
    False = 0,
    TrafficLights = 1,
    CrossRoad = 2,
    CrossRoadLook = 3,
    LookPed = 4,
    LookShop = 5,
    LookAccident = 6,
    FaceoffGang = 7,
    Doubleback = 8,
    HitWall = 9,
    Turn180 = 10,
    Surprise = 11,
    Stuck = 12,
    LookAbout = 13,
    PlayAnimDuck = 14,
    PlayAnimCower = 15,
    PlayAnimTaxi = 16,
    PlayanimHandsUp = 17,
    PlayAnimHandsCower = 18,
    PlayAnimChat = 19,
    FinishFlee = 20,
    SitDown = 21,
    SitDownRvrs = 22,
    SitUp = 23,
    SitIdle = 24,
    UseAtm = 25,
    SunBathePre = 26,
    SunBatheDown = 27,
    SunBatheIdle = 28,
    Riot = 29,
    FastFall = 30,
    Bomber = 31,
    Stripper = 32,
    GroundAttack = 33,
    LanceSitting = 34,
    PlayAnimHandsUpSimple = 35,
}
export enum ObjBuyIceCreamStatus {
    Failed = 0,
    Success = 1,
}
export enum CarLock {
    NotUsed = 0,
    Unlocked = 1,
    Locked = 2,
    LockoutPlayerOnly = 3,
    LockedPlayerInside = 4,
    LockedInitially = 5,
    ForceShutDoors = 6,
    SkipShutDoors = 7,
}
export enum PickupType {
    None = 0,
    InShop = 1,
    OnStreet = 2,
    Once = 3,
    OnceTimeout = 4,
    OnceTimeoutSlow = 5,
    Collectable1 = 6,
    InShopOutOfStock = 7,
    Money = 8,
    MineInactive = 9,
    MineArmed = 10,
    NauticalMineInactive = 11,
    NauticalMineArmed = 12,
    FloatingPackage = 13,
    FloatingPackageFloating = 14,
    OnStreetSlow = 15,
    AssetRevenue = 16,
    PropertyLocked = 17,
    PropertyForSale = 18,
}
export enum ParticleObject {
    PavementSteam = 0,
    PavementSteamSlowmotion = 1,
    WallSteam = 2,
    WallSteamSlowmotion = 3,
    DarkSmoke = 4,
    FireHydrant = 5,
    CarWaterSplash = 6,
    PedWaterSplash = 7,
    SplashesAround = 8,
    SmallFire = 9,
    BigFire = 10,
    DryIce = 11,
    DryIceSlowmotion = 12,
    WaterFountainVert = 13,
    WaterFountainHoriz = 14,
    FireTrail = 15,
    SmokeTrail = 16,
    FireballAndSmoke = 17,
    RocketTrail = 18,
    ExplosionOnce = 19,
    CatalinasGunflash = 20,
    CatalinasShotgunflash = 21,
}
export enum ParticleType {
    Spark = 0,
    SparkSmall,
    WaterSpark,
    WheelDirt,
    Sand,
    WheelWater,
    Blood,
    BloodSmall,
    BloodSpurt,
    Debris,
    Debris2,
    Flyers,
    Water,
    Flame,
    Fireball,
    GunFlash,
    GunFlashNoAnim,
    GunSmoke,
    GunSmoke2,
    CigaretteSmoke,
    Smoke,
    SmokeSlowMotion,
    DryIce,
    TearGas,
    GaragePaintSpray,
    Shard,
    Splash,
    CarFlame,
    Steam,
    Steam2,
    SteamNy,
    SteamNySlowMotion,
    GroundSteam,
    EngineSteam,
    Raindrop,
    RaindropSmall,
    RainSplash,
    RainSplashBiggrow,
    RainSplashUp,
    WaterSpray,
    Waterdrop,
    BloodDrop,
    ExplosionMedium,
    ExplosionLarge,
    ExplosionMfast,
    ExplosionLfast,
    CarSplash,
    BoatSplash,
    BoatThrustjet,
    WaterHydrant,
    WaterCannon,
    ExtinguishSteam,
    PedSplash,
    PedFootDust,
    CarDust,
    HeliDust,
    HeliAttack,
    EngineSmoke,
    EngineSmoke2,
    CarFlameSmoke,
    FireballSmoke,
    PaintSmoke,
    TreeLeaves,
    CarCollisionDust,
    CarDebris,
    BirdDebris,
    HeliDebris,
    ExhaustFumes,
    RubberSmoke,
    BurningRubberSmoke,
    BulletHitSmoke,
    GunshellFirst,
    Gunshell,
    GunshellBump1,
    GunshellBump2,
    RocketSmoke,
    Test,
    BirdFront,
    ShipSide,
    Beastie,
    Raindrop2D,
    HeatHaze,
    HeatHazeInDist,
}
export enum EntityStatus {
    Player = 0,
    PlayerPlaybackFromBuffer = 1,
    Simple = 2,
    Physics = 3,
    Abandoned = 4,
    Wrecked = 5,
    TrainMoving = 6,
    TrainNotMoving = 7,
    Heli = 8,
    Plane = 9,
    PlayerRemote = 10,
    PlayerDisabled = 11,
}
export enum RadarSprite {
    None = 0,
    Centre = 1,
    MapHere = 2,
    North = 3,
    Avery = 4,
    Biker = 5,
    Cortez = 6,
    Diaz = 7,
    Kent = 8,
    Lawyer = 9,
    Phil = 10,
    Bikers = 11,
    Boatyard = 12,
    Malibuclub = 13,
    Cubans = 14,
    Film = 15,
    Gun = 16,
    Haitians = 17,
    Hardware = 18,
    Savehouse = 19,
    Stripclub = 20,
    Ice = 21,
    Kcabs = 22,
    Lovefist = 23,
    Printworks = 24,
    Property = 25,
    Sunyard = 26,
    Spray = 27,
    Tshirt = 28,
    Tommy = 29,
    Phone = 30,
    RadioWildstyle = 31,
    RadioFlash = 32,
    RadioKchat = 33,
    RadioFever = 34,
    RadioVrock = 35,
    RadioVcpr = 36,
    RadioEspantoso = 37,
    RadioEmotion = 38,
    RadioWave = 39,
}
export enum FollowRoute {
    Invalid = 0,
    Once = 1,
    BackForward = 2,
    Loop = 3,
}
export enum Property {
    Malibu = 0,
    Printworks = 1,
    FilmStudio = 2,
    IceCream = 3,
    CarShowroom = 4,
    Taxico = 5,
    Boatyard = 6,
    StripClub = 7,
    Vicepoint = 8,
    LinksView = 9,
    ElSwanko = 10,
    WashingtonStreet = 11,
    OceanHeights = 12,
    SkumoleShack = 13,
    HymanCondo = 14,
}
export enum Bone {
    Root = 0,
    Pelvis = 1,
    Spine = 2,
    Spine1 = 3,
    Neck = 4,
    Head = 5,
    RClavicle = 21,
    RUpperarm = 22,
    RForearm = 23,
    RHand = 24,
    RFingers = 25,
    LClavicle = 31,
    LUpperarm = 32,
    LForearm = 33,
    LHand = 34,
    LFingers = 35,
    LThigh = 41,
    LCalf = 42,
    LFoot = 43,
    RThigh = 51,
    RCalf = 52,
    RFoot = 53,
}
export enum GangType {
    Cuban = 0,
    Haitian = 1,
    Street = 2,
    Diaz = 3,
    Security = 4,
    Biker = 5,
    Player = 6,
    Golfer = 7,
    Gang9 = 8,
}
export enum WeaponSlot {
    Slot1 = 1,
    Slot2 = 2,
    Slot3 = 3,
    Slot4 = 4,
    Slot5 = 5,
    Slot6 = 6,
    Slot7 = 7,
    Slot8 = 8,
    Slot9 = 9,
    Slot10 = 10,
}
export enum WanderDirection {
    North = 0,
    NorthEast = 1,
    East = 2,
    SouthEast = 3,
    South = 4,
    SouthWest = 5,
    West = 6,
    NorthWest = 7,
}
export enum RadioChannel {
    Wildstyle = 0,
    FlashFM = 1,
    KChat = 2,
    Fever = 3,
    VRock = 4,
    VCPR = 5,
    RadioEspantoso = 6,
    Emotion = 7,
    Wave = 8,
    Ambient = 9,
    Off = 10,
    Police = 23,
}
export enum CoronaType {
    Star = 0,
    Normal = 1,
    Moon = 2,
    Reflect = 3,
    Headlight = 4,
    Hex = 5,
    Circle = 6,
    Ring = 7,
    Streak = 8,
}
export enum PlayerMood {
    Calm = 0,
    PissedOff = 1,
    Angry = 2,
    Wisecracking = 3,
}
export enum Font {
    Bank = 0,
    Standard = 1,
    Heading = 2,
    Japanese = 3,
}
export enum SeekOrigin {
    Begin = 0,
    Current = 1,
    End = 2,
}
export enum KeyCode {
    LeftButton = 1,
    RightButton = 2,
    Cancel = 3,
    MiddleButton = 4,
    CustomButton1 = 5,
    CustomButton2 = 6,
    Back = 8,
    Tab = 9,
    Clear = 12,
    Return = 13,
    Shift = 16,
    Ctrl = 17,
    Pause = 19,
    Capital = 20,
    Kana = 21,
    Junja = 23,
    Final = 24,
    Kanji = 25,
    Escape = 27,
    Convert = 28,
    NonConvert = 29,
    Accept = 30,
    ModeChange = 31,
    Space = 32,
    Prior = 33,
    Next = 34,
    End = 35,
    Home = 36,
    Left = 37,
    Up = 38,
    Right = 39,
    Down = 40,
    Select = 41,
    Print = 42,
    Execute = 43,
    Snapshot = 44,
    Insert = 45,
    Delete = 46,
    Help = 47,
    Num0 = 48,
    Num1 = 49,
    Num2 = 50,
    Num3 = 51,
    Num4 = 52,
    Num5 = 53,
    Num6 = 54,
    Num7 = 55,
    Num8 = 56,
    Num9 = 57,
    A = 65,
    B = 66,
    C = 67,
    D = 68,
    E = 69,
    F = 70,
    G = 71,
    H = 72,
    I = 73,
    J = 74,
    K = 75,
    L = 76,
    M = 77,
    N = 78,
    O = 79,
    P = 80,
    Q = 81,
    R = 82,
    S = 83,
    T = 84,
    U = 85,
    V = 86,
    W = 87,
    X = 88,
    Y = 89,
    Z = 90,
    LeftWin = 91,
    RightWin = 92,
    Apps = 93,
    Sleep = 95,
    NumPad0 = 96,
    NumPad1 = 97,
    NumPad2 = 98,
    NumPad3 = 99,
    NumPad4 = 100,
    NumPad5 = 101,
    NumPad6 = 102,
    NumPad7 = 103,
    NumPad8 = 104,
    NumPad9 = 105,
    Multiply = 106,
    Add = 107,
    Separator = 108,
    Subtract = 109,
    Decimal = 110,
    Divide = 111,
    F1 = 112,
    F2 = 113,
    F3 = 114,
    F4 = 115,
    F5 = 116,
    F6 = 117,
    F7 = 118,
    F8 = 119,
    F9 = 120,
    F10 = 121,
    F11 = 122,
    F12 = 123,
    F13 = 124,
    F14 = 125,
    F15 = 126,
    F16 = 127,
    F17 = 128,
    F18 = 129,
    F19 = 130,
    F20 = 131,
    F21 = 132,
    F22 = 133,
    F23 = 134,
    F24 = 135,
    NumLock = 144,
    Scroll = 145,
    OemFjjisho = 146,
    OemFjmasshou = 147,
    OemFjtouroku = 148,
    OemFjloya = 149,
    OemFjroya = 150,
    LeftShift = 160,
    RightShift = 161,
    LeftControl = 162,
    RightControl = 163,
    LeftMenu = 164,
    RightMenu = 165,
    BrowserBack = 166,
    BrowserForward = 167,
    BrowserRefresh = 168,
    BrowserStop = 169,
    BrowserSearch = 170,
    BrowserFavorites = 171,
    BrowserHome = 172,
    VolumeMute = 173,
    VolumeDown = 174,
    VolumeUp = 175,
    MediaNextTrack = 176,
    MediaPrevTrack = 177,
    MediaStop = 178,
    MediaPlaypause = 179,
    LaunchMail = 180,
    LaunchMediaselect = 181,
    LaunchApp1 = 182,
    LaunchApp2 = 183,
    Oem1 = 186,
    OemPlus = 187,
    OemComma = 188,
    OemMinus = 189,
    OemPeriod = 190,
    Oem2 = 191,
    Oem3 = 192,
    Abntc1 = 193,
    Abntc2 = 194,
    Oem4 = 219,
    Oem5 = 220,
    Oem6 = 221,
    Oem7 = 222,
    Oem8 = 223,
    OemAx = 225,
    Oem102 = 226,
    IcoHelp = 227,
    Ico00 = 228,
    Processkey = 229,
    Icoclear = 230,
    Packet = 231,
    OemReset = 233,
    OemJump = 234,
    OemPa1 = 235,
    OemPa2 = 236,
    OemPa3 = 237,
    OemWsctrl = 238,
    OemCusel = 239,
    OemAttn = 240,
    OemFinish = 241,
    OemCopy = 242,
    OemAuto = 243,
    OemEnlw = 244,
    OemBackTab = 245,
    Attn = 246,
    Crsel = 247,
    Exsel = 248,
    Ereof = 249,
    Play = 250,
    Zoom = 251,
    Noname = 252,
    Pa1 = 253,
    OemClear = 254,
}
export enum ImGuiCond {
    None = 0,
    Always = 1,
    Once = 2,
    FirstUseEver = 4,
    Appearing = 8,
}
export enum PadId {
    Pad1 = 0,
    Pad2 = 1,
}
export enum ImGuiCol {
    Text = 0,
    TextDisabled = 1,
    WindowBg = 2,
    ChildBg = 3,
    PopupBg = 4,
    Border = 5,
    BorderShadow = 6,
    FrameBg = 7,
    FrameBgHovered = 8,
    FrameBgActive = 9,
    TitleBg = 10,
    TitleBgActive = 11,
    TitleBgCollapsed = 12,
    MenuBarBg = 13,
    ScrollbarBg = 14,
    ScrollbarGrab = 15,
    ScrollbarGrabHovered = 16,
    ScrollbarGrabActive = 17,
    CheckMark = 18,
    SliderGrab = 19,
    SliderGrabActive = 20,
    Button = 21,
    ButtonHovered = 22,
    ButtonActive = 23,
    Header = 24,
    HeaderHovered = 25,
    HeaderActive = 26,
    Separator = 27,
    SeparatorHovered = 28,
    SeparatorActive = 29,
    ResizeGrip = 30,
    ResizeGripHovered = 31,
    ResizeGripActive = 32,
    Tab = 33,
    TabHovered = 34,
    TabActive = 35,
    TabUnfocused = 36,
    TabUnfocusedActive = 37,
    PlotLines = 38,
    PlotLinesHovered = 39,
    PlotHistogram = 40,
    PlotHistogramHovered = 41,
    TableHeaderBg = 42,
    TableBorderStrong = 43,
    TableBorderLight = 44,
    TableRowBg = 45,
    TableRowBgAlt = 46,
    TextSelectedBg = 47,
    DragDropTarget = 48,
    NavHighlight = 49,
    NavWindowingHighlight = 50,
    NavWindowingDimBg = 51,
    ModalWindowDimBg = 52,
}
export enum ImGuiStyleVar {
    Alpha = 0,
    DisabledAlpha = 1,
    WindowPadding = 2,
    WindowRounding = 3,
    WindowBorderSize = 4,
    WindowMinSize = 5,
    WindowTitleAlign = 6,
    ChildRounding = 7,
    ChildBorderSize = 8,
    PopupRounding = 9,
    PopupBorderSize = 10,
    FramePadding = 11,
    FrameRounding = 12,
    FrameBorderSize = 13,
    ItemSpacing = 14,
    ItemInnerSpacing = 15,
    IndentSpacing = 16,
    CellPadding = 17,
    ScrollbarSize = 18,
    ScrollbarRounding = 19,
    GrabMinSize = 20,
    GrabRounding = 21,
    TabRounding = 22,
    ButtonTextAlign = 23,
    SelectableTextAlign = 24,
}
export enum DrivingMode {
    StopForCars = 0,
    SlowDownForCars = 1,
    AvoidCars = 2,
    PloughThrough = 3,
    StopForCarsIgnoreLights = 4,
}
export enum WheelId {
    FrontLeft = 0,
    RearLeft = 1,
    FrontRight = 2,
    RearRight = 3,
    Any = 4,
    BikeFront = 0,
    BikeRear = 1,
}
export enum SeatId {
    FrontRight = 0,
    RearLeft = 1,
    RearRight = 2,
    Passenger4 = 3,
    Passenger5 = 4,
    Passenger6 = 5,
    Passenger7 = 6,
    Passenger8 = 7,
    BikeRear = 0,
}
export enum FileMode {
    ReadText = "rt",
    WriteText = "wt",
    AppendText = "at",
    ReadBinary = "rb",
    WriteBinary = "wb",
    AppendBinary = "ab",
}
export enum VehicleModel {
    Landstalker = 130,
    Idaho = 131,
    Stinger = 132,
    Linerunner = 133,
    Perennial = 134,
    Sentinel = 135,
    Rio = 136,
    Firetruck = 137,
    Trashmaster = 138,
    Stretch = 139,
    Manana = 140,
    Infernus = 141,
    Voodoo = 142,
    Pony = 143,
    Mule = 144,
    Cheetah = 145,
    Ambulance = 146,
    FBI_Washington = 147,
    Moonbeam = 148,
    Esperanto = 149,
    Taxi = 150,
    Washington = 151,
    Bobcat = 152,
    MrWhoopee = 153,
    BF_Injection = 154,
    Hunter = 155,
    Police = 156,
    Enforcer = 157,
    Securicar = 158,
    Banshee = 159,
    Predator = 160,
    Bus = 161,
    Rhino = 162,
    BarracksOL = 163,
    CubanHermes = 164,
    Helicopter = 165,
    Angel = 166,
    Coach = 167,
    Cabbie = 168,
    Stallion = 169,
    Rumpo = 170,
    RC_Bandit = 171,
    RomerosHearse = 172,
    Packer = 173,
    SentinelXS = 174,
    Admiral = 175,
    Squalo = 176,
    SeaSparrow = 177,
    PizzaBoy = 178,
    GangBurrito = 179,
    Dodo = 181,
    Speeder = 182,
    Reefer = 183,
    Tropic = 184,
    Flatbed = 185,
    Yankee = 186,
    Caddy = 187,
    ZebraCab = 188,
    TopFun = 189,
    Skimmer = 190,
    PCJ600 = 191,
    Faggio = 192,
    Freeway = 193,
    RC_Baron = 194,
    RC_Raider = 195,
    Glendale = 196,
    Oceanic = 197,
    Sanchez = 198,
    Sparrow = 199,
    Patriot = 200,
    LoveFist = 201,
    CoastGuard = 202,
    Dinghy = 203,
    Hermes = 204,
    Sabre = 205,
    SabreTurbo = 206,
    Phoenix = 207,
    Walton = 208,
    Regina = 209,
    Comet = 210,
    Deluxo = 211,
    Burrito = 212,
    SpandExpress = 213,
    Marquis = 214,
    BaggageHandler = 215,
    KaufmanCab = 216,
    Maverick = 217,
    VCN_Maverick = 218,
    Rancher = 219,
    FBI_Rancher = 220,
    Virgo = 221,
    Greenwood = 222,
    CubanJetmax = 223,
    HotringRacer = 224,
    Sandking = 225,
    BlistaCompact = 226,
    PoliceMaverick = 227,
    Boxville = 228,
    Benson = 229,
    MesaGrande = 230,
    RC_Goblin = 231,
    HotringRacer2 = 232,
    HotringRacer3 = 233,
    BloodringBanger = 234,
    BloodringBanger2 = 235,
    Cheetah2 = 236,
}
export enum AnimationGroupId {
    Std = 0,
    Van,
    Coach,
    BikeStandard,
    BikeVespa,
    BikeHarley,
    BikeDirt,
    Unarmed,
    Screwdriver,
    Knife,
    Baseballbat,
    Golfclub,
    Chainsaw,
    Python,
    Colt,
    Shotgun,
    Buddy,
    Tec,
    Uzi,
    Rifle,
    M60,
    Sniper,
    Throw,
    Flamethrower,
    Medic,
    Sunbathe,
    PlayerIdle,
    Riot,
    Strip,
    Lance,
    Player,
    Playerrocket,
    Player1Armed,
    Player2Armed,
    Playerbbbat,
    Playerchainsaw,
    Shuffle,
    Old,
    Gang1,
    Gang2,
    Fat,
    Oldfat,
    Jogger,
    Woman,
    Womanshop,
    Busywoman,
    Sexywoman,
    Fatwoman,
    Oldwoman,
    Jogwoman,
    Panicchunky,
    Skate,
    Playerback,
    Playerleft,
    Playerright,
    Rocketback,
    Rocketleft,
    Rocketright,
    Chainsawback,
    Chainsawleft,
    Chainsawright,
}
export enum AnimationId {
    StdWalk = 0,
    StdRun,
    StdRunfast,
    StdIdle,
    StdStartwalk,
    StdRunstop1,
    StdRunstop2,
    StdIdleCam,
    StdIdleHbhb,
    StdIdleTired,
    StdIdleBiggun,
    StdChat,
    StdHailtaxi,
    StdKoFront,
    StdKoLeft,
    StdKoBack,
    StdKoRight,
    StdKoShotFace,
    StdKoShotStomach,
    StdKoShotArmL,
    StdKoShotArmR,
    StdKoShotLegL,
    StdKoShotLegR,
    StdSpinforwardLeft,
    StdSpinforwardRight,
    StdHighimpactFront,
    StdHighimpactLeft,
    StdHighimpactBack,
    StdHighimpactRight,
    StdHitbygunFront,
    StdHitbygunLeft,
    StdHitbygunBack,
    StdHitbygunRight,
    StdHitFront,
    StdHitLeft,
    StdHitBack,
    StdHitRight,
    StdHitFloor,

    StdHitBodyblow,
    StdHitChest,
    StdHitHead,
    StdHitWalk,

    StdHitWall,
    StdHitFloorFront,
    StdHitBehind,
    StdFightIdle,
    StdFight2Idle,
    StdFightShuffleF,

    StdFightBodyblow,
    StdFightHead,
    StdFightKick,
    StdFightKnee,
    StdFightLhook,
    StdFightPunch,
    StdFightRoundhouse,
    StdFightLongkick,

    StdPartialPunch,

    StdFightJab,
    StdFightElbowL,
    StdFightElbowR,
    StdFightBkickL,
    StdFightBkickR,

    StdDetonate,
    StdPunch,
    StdPartialpunch,
    StdKickground,

    StdThrowUnder,
    StdFightShuffleB,

    StdJackedcarRhs,
    StdJackedcarLoRhs,
    StdJackedcarLhs,
    StdJackedcarLoLhs,
    StdQuickjack,
    StdQuickjacked,
    StdCarAlignDoorLhs,
    StdCarAlignhiDoorLhs,
    StdCarOpenDoorLhs,
    StdCardoorLockedLhs,
    StdCarPullOutPedLhs,
    StdCarPullOutPedLoLhs,
    StdCarGetInLhs,
    StdCarGetInLoLhs,
    StdCarCloseDoorLhs,
    StdCarCloseDoorLoLhs,
    StdCarCloseDoorRollingLhs,
    StdCarCloseDoorRollingLoLhs,
    StdCarJumpInLoLhs,
    StdGetoutLhs,
    StdGetoutLoLhs,
    StdCarCloseLhs,
    StdCarAlignDoorRhs,
    StdCarAlignhiDoorRhs,
    StdCarOpenDoorRhs,
    StdCardoorLockedRhs,
    StdCarPullOutPedRhs,
    StdCarPullOutPedLoRhs,
    StdCarGetInRhs,
    StdCarGetInLoRhs,
    StdCarCloseDoorRhs,
    StdCarCloseDoorLoRhs,
    StdCarShuffleRhs,
    StdCarShuffleLoRhs,
    StdCarSit,
    StdCarSitLo,
    StdCarSitP,
    StdCarSitPLo,
    StdCarDriveLeft,
    StdCarDriveRight,
    StdCarDriveLeftLo,
    StdCarDriveRightLo,
    StdCarDrivebyLeft,
    StdCarDrivebyRight,
    StdCarDrivebyLeftLo,
    StdCarDrivebyRightLo,
    StdCarLookbehind,
    StdBoatDrive,
    StdBoatDriveLeft,
    StdBoatDriveRight,
    StdBoatLookbehind,

    StdBikePickupLhs,
    StdBikePickupRhs,
    StdBikePullupLhs,
    StdBikePullupRhs,
    StdBikeElbowLhs,
    StdBikeElbowRhs,
    StdBikeFalloff,
    StdBikeFallback,

    StdGetoutRhs,
    StdGetoutLoRhs,
    StdCarCloseRhs,
    StdCarHookertalk,

    StdTrainGetin,
    StdTrainGetout,

    StdCrawloutLhs,
    StdCrawloutRhs,
    StdRolloutLhs,
    StdRolloutRhs,

    StdGetUp,
    StdGetUpLeft,
    StdGetUpRight,
    StdGetUpFront,
    StdJumpLaunch,
    StdJumpGlide,
    StdJumpLand,
    StdFall,
    StdFallGlide,
    StdFallLand,
    StdFallCollapse,
    StdFallOnback,
    StdFallOnfront,

    StdEvadeStep,
    StdEvadeDive,
    StdXpressScratch,
    StdRoadcross,
    StdTurn180,
    StdArrest,
    StdDrown,
    StdDuckDown,
    StdDuckLow,

    StdDuckWeapon,

    StdRblockShoot,
    StdHandsup,
    StdHandscower,
    StdPartialFucku,
    StdPhoneIn,
    StdPhoneOut,
    StdPhoneTalk,

    StdSeatDown,
    StdSeatUp,
    StdSeatIdle,
    StdSeatRvrs,
    StdAtm,
    StdAbseil,

    StdVanOpenDoorRearLhs,
    StdVanGetInRearLhs,
    StdVanCloseDoorRearLhs,
    StdVanGetOutRearLhs,
    StdVanOpenDoorRearRhs,
    StdVanGetInRearRhs,
    StdVanCloseDoorRearRhs,
    StdVanGetOutRearRhs,

    StdCoachOpenLhs,
    StdCoachOpenRhs,
    StdCoachGetInLhs,
    StdCoachGetInRhs,
    StdCoachGetOutLhs,

    BikeRide,
    BikeReady,
    BikeLeft,
    BikeRight,
    BikeLeanb,
    BikeLeanf,
    BikeWalkback,
    BikeJumponLhs,
    BikeJumponRhs,
    BikeKick,
    BikeHit,
    BikeGetoffLhs,
    BikeGetoffRhs,
    BikeGetoffBack,
    BikeDrivebyLhs,
    BikeDrivebyRhs,
    BikeDrivebyForward,
    BikeRideP,

    Attack1,
    Attack2,
    AttackExtra1,
    AttackExtra2,
    Attack3,

    SunbatheIdle,
    SunbatheDown,
    SunbatheUp,
    SunbatheEscape,

    MedicCpr,

    PlayerIdle1,
    PlayerIdle2,
    PlayerIdle3,
    PlayerIdle4,

    RiotAngry,
    RiotAngryB,
    RiotChant,
    RiotPunches,
    RiotShout,
    RiotChallenge,
    RiotFuckyou,

    StripA,
    StripB,
    StripC,
    StripD,
    StripE,
    StripF,
    StripG,
}
export enum MoveState {
    PedmoveNone = 0,
    PedmoveStill,
    PedmoveWalk,
    PedmoveJog,
    PedmoveRun,
    PedmoveSprint,
    PedmoveThrown,
}
