export const ReHud = {
    'Save': 'Save settings',
    'TurnON': 'Enable new HUD',
    'UseBars': 'Use bars',
    'UseSeparator': 'Use separator',
    'BarSettings': 'Bars settings',
    'BgAlpha': 'Background transparency',
    'MdAlpha': 'Middle colour transparency',
    'FgAlpha': 'Foreground transparency',
    'SepColour': 'Separator colour',
    'ApplySepCol': 'Apply separator colour',
    'Shadow': 'Shadow instead of outline',
    'DefClock': 'Standard clock',
    'HrsCentre': 'Hours in centre',
    'WantedStars': 'Wanted level stars',
    'Font': 'Font:',
    'Gothic': 'Gothic',
    'Subtitles': 'Subtitles',
    'Menu': 'Menu',
    'Pricedown': 'Pricedown',
    'Scale': 'HUD size',
    'ShadowSize': 'Shadow size',
    'OutlineSize': 'Outline size',
    'RadarMapColour': 'Radar & map colour',
    'CrosshairColour': 'Crosshair colour',
    'About': 'About',
    'Authors': 'Authors:\n- Mod by Vital (Vitaly Ulyanov)\n- CLEO Redux by Seemann\n- ImGui support by Grinch',
    'Help': 'Thanks for help to: Seemann, Grinch, Alexander Lukhnovich, Bloodriver',
    'Ideas': 'Thanks for ideas to: Seemann, Bloodriver'
};