export const Texts = {
    'English': {
        'Opacity': 'Opacity',
        'Tabs': 'Player, Vehicle, World, Position, Display, About',
        'Player': 'Player',
        'Vehicle': 'Vehicle',
        'World': 'World',
        'Position': 'Position',
        'About': 'About',
        'Mode': 'Mode',
        'Reset': 'Reset',
        'GameChoice': 'GAME\'S CHOICE',
        'AlwaysOFF': 'ALWAYS OFF',
        'AlwaysON': 'ALWAYS ON',

        'General': 'General',
        'Health': 'Health',
        'Armour': 'Armour',
        'Money': 'Money',
        'Wanted': 'Wanted level',
        'MaxWL': 'Max wanted level',
        'LockPlr': 'Lock movement and camera',
        'FreezePlr': 'Lock movement',
        'StayOnBike': 'Stay on bike',
        'InfiniteSprint': 'Infinite sprint',
        'IgnoredByCops': 'Ignored by police',
        'IgnoredByAll': 'Ignored by everyone',

        'Immunities': 'Proofs',
        'ImmBullet': 'Bullet',
        'ImmFire': 'Fire',
        'ImmExplosion': 'Explosion',
        'ImmCollision': 'Collision',
        'ImmMelee': 'Melee',

        'TyresProof': 'Bulletproof tyres',
        'HeavyCar': 'Make vehicle heavy',
        'Fix': 'Fix',
        'DirtLevel': 'Dirt level',
        'Spawner': 'Spawn a vehicle',
        'Vehicles': 'Vehicle',
        'Colours': 'Colours',
        'Colour': 'Colour',
        'Paintjob': 'Paintjob',
        'Categories': 'Primary, Secondary, Extra 1, Extra 2',
        'ColsPerRow': 'Colours per row',
        'HydraulicsAdd': 'Add hydraulics',
        'HydraulicsRemove': 'Remove hydraulics',

        'Population': 'Population',
        'Gravity': 'Gravity',
        'Time': 'Time',
        'Hours': 'Hours',
        'Minutes': 'Minutes',
        'GameSpeed': 'Game speed (%)',
        'LockTime': 'Lock time',
        'Weather': 'Weather',
        'CurrentWeather': 'Current weather',
        'NextWeather': 'Next weather',
        'ResetWeather': 'Reset weather',
        'PedDensChange': 'Change pedestrian density',
        'PedDensity': 'Pedestrian density',
        'CarDensChange': 'Change car density',
        'CarDensity': 'Car density',
        'ClearArea': 'Clear area',
        'Radius': 'Radius',
        'Wind': 'Custom wind speed',
        'WindX': 'Wind speed (X)',
        'WindY': 'Wind speed (Y)',
        'WindZ': 'Wind speed (Z)',

        'CurPosition': 'Current position',
        'Teleport': 'Teleport',
        'InstantTeleport': 'Instant teleport',
        'InstTpReset': 'Disable on closing the menu',
        'Modes': 'Fast, Precise, Text input',
        'CoordX': 'X',
        'CoordY': 'Y',
        'CoordZ': 'Z',
        'Heading': 'Heading',
        'Interior': 'Interior',
        'Coords': 'Teleport to coordinates',
        'Waypoint': 'Teleport to waypoint',

        'Hud': 'HUD',
        'Radar': 'Radar',
        'Widescreen': 'Widescreen',
        'NightVision': 'Night vision',
        'ThermalVision': 'Infrared vision',

        'HowTo': 'Choose the necessary category and subcategory, then adjust settings sliders\' grab or just press it to apply changes.',
        'About0': 'Authors',
        'About1': '\t\tMod by Vital (Vitaly Ulyanov)',
        'About2': '\t\tCLEO Redux by Seemann',
        'About3': '\t\tImGui support by Grinch',
        'Help': 'Thanks for help to:',
        'Help1': '\t\tSeemann, Bloodriver',
        'WindowControl': 'Window control',
        'WinCtrl1': 'Hold ~ and press:',
        'WinCtrl2': '\t\tHome - reset window',
        'WinCtrl3': '\t\tEnd - fill screen',
        'WinCtrl4': '\t\tArrow buttons - snap to sides/corners'
    }
};