export const Texts = {
    'English': {
        'Opacity': 'Menu background opacity',
        'Tabs': 'Player, Vehicle, World, Position, About',
        'Player': 'Player',
        'Vehicle': 'Vehicle',
        'World': 'World',
        'Position': 'Position',
        'About': 'About',
        'Mode': 'Mode',

        'General': 'General',
        'Health': 'Health',
        'Armour': 'Armour',
        'Money': 'Money',
        'Wanted': 'Wanted level',
        'MaxWL': 'Max wanted level',
        'StayOnBike': 'Stay on bike',

        'Immunities': 'Proofs',
        'ImmBullet': 'Bullet',
        'ImmFire': 'Fire',
        'ImmExplosion': 'Explosion',
        'ImmCollision': 'Collision',
        'ImmMelee': 'Melee',

        'TyresProof': 'Bulletproof tyres',
        'HeavyCar': 'Make vehicle heavy',
        'Fix': 'Fix',
        'DirtLevel': 'Dirt level',
        'Spawner': 'Spawn a vehicle',
        'Vehicles': 'Vehicle',
        'Colours': 'Colours',
        'Colour': 'Colour',
        'Paintjob': 'Paintjob',
        'Categories': 'Primary, Secondary, Extra 1, Extra 2',
        'ColsPerRow': 'Colours per row',

        'Population': 'Population',
        'Time': 'Time',
        'Hours': 'Hours',
        'Minutes': 'Minutes',
        'GameSpeed': 'Game speed (%)',
        'LockTime': 'Lock time',
        'Weather': 'Weather',
        'CurrentWeather': 'Current weather',
        'NextWeather': 'Next weather',
        'ResetWeather': 'Reset weather',
        'PedDensity': 'Pedestrian density',
        'CarDensity': 'Car density',
        'ClearArea': 'Clear area',
        'Radius': 'Radius',

        'CurPosition': 'Current position',
        'Teleport': 'Teleport',
        'InstantTeleport': 'Instant teleport',
        'InstTpReset': 'Disable on closing the menu',
        'Modes': 'Fast, Precise, Text input',
        'CoordX': 'X',
        'CoordY': 'Y',
        'CoordZ': 'Z',
        'Heading': 'Heading',
        'Interior': 'Interior',
        'Coords': 'Teleport to coordinates',
        'Waypoint': 'Teleport to waypoint',

        'HowTo': 'Choose the necessary category and subcategory, then adjust settings sliders\' grab or just press it to apply changes.',
        'About0': 'Authors',
        'About1': '\t\tMod by Vital (Vitaly Ulyanov)',
        'About2': '\t\tCLEO Redux by Seemann',
        'About3': '\t\tImGui support by Grinch',
        'Help': 'Thanks for help to:',
        'Help1': '\t\t'
    }
};