export const ReHud = {
    'Save': 'Сохранить настройки',
    'TurnON': 'Включить новый HUD',
    'UseBars': 'Шкалы',
    'UseSeparator': 'Разделитель',
    'BarSettings': 'Настройки шкал',
    'BgAlpha': 'Прозрачность фонового цвета',
    'MdAlpha': 'Прозрачность среднего цвета',
    'FgAlpha': 'Прозрачность переднего цвета',
    'SepColour': 'Цвет разделителя',
    'ApplySepCol': 'Применить цвет разделителя',
    'Shadow': 'Тень вместо обводки',
    'DefClock': 'Обычные часы',
    'HrsCentre': 'Показатель часа в центре',
    'WantedStars': 'Звёздочки розыска',
    'Font': 'Шрифт:',
    'Gothic': 'Готический',
    'Subtitles': 'Субтитры',
    'Menu': 'Меню',
    'Pricedown': 'Pricedown',
    'Scale': 'Размер HUD’а',
    'ShadowSize': 'Размер тени',
    'OutlineSize': 'Размер обводки',
    'About': 'О модификации',
    'Authors': 'Авторы:\n- Мод — Vital (Виталий Ульянов)\n- CLEO Redux — Seemann\n- Поддержка ImGui — Grinch',
    'Help': 'Помогали: Seemann, Grinch, Александр Лухнович, Bloodriver',
    'Ideas': 'Предлагали идеи: Seemann, Bloodriver'
};