import { AltMenu } from "../../altMenu[mem]";
import { plc, plr } from "../sharedConstants";

interface ClothesItem {
    name: string;
    model: string;
    texture: string;
}
interface Part {
    id: int;
    name: string;
    items: ClothesItem[];
    menu?: AltMenu;
    clearBodyPart?: int[];
    camOffset: [float, float, float];
    camRotation: [float, float, float];
}

// Clothes
let torso: Part = {
    id: 0,
    name: "#TORSO",
    items: [
        { name: "VESTA", model: "vest", texture: "vestblack" },
        { name: "VESTWH", model: "vest", texture: "vest" },
        { name: "TSRTHS1", model: "tshirt2", texture: "tshirt2horiz" },
        { name: "TSHIRTC", model: "tshirt", texture: "tshirtwhite" },
        { name: "LOVETS1", model: "tshirt", texture: "tshirtilovels" },
        { name: "TSHIRTA", model: "tshirt", texture: "tshirtblunts" },
        { name: "SHIRTBB", model: "shirtb", texture: "shirtbplaid" },
        { name: "CHEKSH1", model: "shirtb", texture: "shirtbcheck" },
        { name: "FIELDA", model: "field", texture: "field" },
        { name: "ERSTSH1", model: "tshirt", texture: "tshirterisyell" },
        { name: "ERISTS2", model: "tshirt", texture: "tshirterisorn" },
        { name: "TRAKER1", model: "trackytop1", texture: "trackytop2eris" },
        { name: "BASJCT2", model: "bbjack", texture: "bbjackrim" },
        { name: "BASJCT3", model: "bbjack", texture: "bballjackrstar" },
        { name: "BASKA", model: "baskball", texture: "baskballdrib" },
        { name: "BASKC", model: "baskball", texture: "baskballrim" },
        { name: "TSHRT69", model: "tshirt", texture: "sixtyniners" },
        { name: "BANDITS", model: "baseball", texture: "bandits" },
        { name: "PROSHRD", model: "tshirt", texture: "tshirtprored" },
        { name: "PROTSH1", model: "tshirt", texture: "tshirtproblk" },
        { name: "TRAKPR1", model: "trackytop1", texture: "trackytop1pro" },
        { name: "HCKYTOP", model: "sweat", texture: "hockeytop" },
        { name: "BBJERY1", model: "sleevt", texture: "bbjersey" },
        { name: "SHELSUT", model: "trackytop1", texture: "shellsuit" },
        { name: "HEATSH1", model: "tshirt", texture: "tshirtheatwht" },
        { name: "TSHRBO1", model: "tshirt", texture: "tshirtbobomonk" },
        { name: "TSHRBO2", model: "tshirt", texture: "tshirtbobored" },
        { name: "TSRTBA1", model: "tshirt", texture: "tshirtbase5" },
        { name: "TSRTSB1", model: "tshirt", texture: "tshirtsuburb" },
        { name: "HODMRC1", model: "hoodya", texture: "hoodyamerc" },
        { name: "HODBSE1", model: "hoodya", texture: "hoodyabase5" },
        { name: "HODRST1", model: "hoodya", texture: "hoodyarockstar" },
        { name: "WCOATA", model: "wcoat", texture: "wcoatblue" },
        { name: "COACHA", model: "coach", texture: "coach" },
        { name: "COACHB", model: "coach", texture: "coachsemi" },
        { name: "RSTRSWE", model: "sweat", texture: "sweatrstar" },
        { name: "HOODB", model: "hoodyA", texture: "hoodyAblue" },
        { name: "HOODBL", model: "hoodyA", texture: "hoodyAblack" },
        { name: "HOODG", model: "hoodyA", texture: "hoodyAgreen" },
        { name: "SLEVB1", model: "sleevt", texture: "sleevtbrown" },
        { name: "BSHIRT", model: "shirta", texture: "shirtablue" },
        { name: "YSHIRT", model: "shirta", texture: "shirtayellow" },
        { name: "GSHIRT", model: "shirta", texture: "shirtagrey" },
        { name: "SHTBG1", model: "shirtb", texture: "shirtbgang" },
        { name: "TSHZIP1", model: "tshirt", texture: "tshirtzipcrm" },
        { name: "TSHZIP2", model: "tshirt", texture: "tshirtzipgry" },
        { name: "DENJCK1", model: "denim", texture: "denimfade" },
        { name: "BOWLSH1", model: "hawaii", texture: "bowling" },
        { name: "HODJCK1", model: "hoodjack", texture: "hoodjackbeige" },
        { name: "BASKB", model: "baskball", texture: "baskballloc" },
        { name: "TSHIRTB", model: "tshirt", texture: "tshirtlocgrey" },
        { name: "TSHRTMG", model: "tshirt", texture: "tshirtmaddgrey" },
        { name: "TSRTMGN", model: "tshirt", texture: "tshirtmaddgrn" },
        { name: "SUT1GRY", model: "suit1", texture: "suit1grey" },
        { name: "SUT1BLK", model: "suit1", texture: "suit1blk" },
        { name: "BIKERJ", model: "leather", texture: "leather" },
        { name: "PAINT1", model: "painter", texture: "painter" },
        { name: "HAWAI1", model: "hawaii", texture: "hawaiiwht" },
        { name: "HAWAI2", model: "hawaii", texture: "hawaiired" },
        { name: "SPRJCT", model: "trackytop1", texture: "sportjack" },
        { name: "SUIT1", model: "suit1", texture: "suit1red" },
        { name: "SUIT2", model: "suit1", texture: "suit1blue" },
        { name: "SUIT3", model: "suit1", texture: "suit1yellow" },
        { name: "SUT2GRN", model: "suit2", texture: "suit2grn" },
        { name: "TUXEDO", model: "suit2", texture: "tuxedo" },
        { name: "SUITGNG", model: "suit1", texture: "suit1gang" },
        { name: "LETTER", model: "sleevt", texture: "letter" },
        { name: "REMCLT", model: undefined, texture: undefined },
    ],
    camOffset: [-0.35, 1.7, 0.85],
    camRotation: [0, 0, 0.4],
};
let legs: Part = {
    id: 2,
    name: "#LEGS",
    items: [
        { name: "WORKA", model: "worktr", texture: "worktrcamogrn" },
        { name: "WORKB", model: "worktr", texture: "worktrcamogry" },
        { name: "WORKC", model: "worktr", texture: "worktrgrey" },
        { name: "WORKD", model: "worktr", texture: "worktrkhaki" },
        { name: "TRABOTA", model: "tracktr", texture: "tracktr" },
        { name: "TRAKERI", model: "tracktr", texture: "tracktreris" },
        { name: "JEANSBL", model: "jeans", texture: "jeansdenim" },
        { name: "BOXBLK", model: "legs", texture: "legsblack" },
        { name: "BOXHRT", model: "legs", texture: "legsheart" },
        { name: "BEITROS", model: "chinosb", texture: "biegetr" },
        { name: "TRACKT1", model: "tracktr", texture: "tracktrpro" },
        { name: "TRACKT2", model: "tracktr", texture: "tracktrwhstr" },
        { name: "TRACKT3", model: "tracktr", texture: "tracktrblue" },
        { name: "TRACKT4", model: "tracktr", texture: "tracktrgang" },
        { name: "BOXSRT1", model: "boxingshort", texture: "bbshortwht" },
        { name: "BOXSRT2", model: "boxingshort", texture: "boxshort" },
        { name: "BOXSRT3", model: "boxingshort", texture: "bbshortred" },
        { name: "SHELBOT", model: "tracktr", texture: "shellsuittr" },
        { name: "SHORT1", model: "shorts", texture: "shortsgrey" },
        { name: "SHORT2", model: "shorts", texture: "shortskhaki" },
        { name: "CHONG1", model: "chonger", texture: "chongergrey" },
        { name: "CHONG2", model: "chonger", texture: "chongergang" },
        { name: "CHONG3", model: "chonger", texture: "chongerred" },
        { name: "CHONG4", model: "chonger", texture: "chongerblue" },
        { name: "SHORT3", model: "shorts", texture: "shortsgang" },
        { name: "DENIM1", model: "jeans", texture: "denimsgang" },
        { name: "DENIM2", model: "jeans", texture: "denimsred" },
        { name: "CHINBIE", model: "chinosb", texture: "chinosbiege" },
        { name: "CHINOK", model: "chinosb", texture: "chinoskhaki" },
        { name: "CUTCHI", model: "shorts", texture: "cutoffchinos" },
        { name: "CHINO3", model: "chinosb", texture: "chinosblack" },
        { name: "CHINO4", model: "chinosb", texture: "chinosblue" },
        { name: "LEATHA", model: "leathertr", texture: "leathertr" },
        { name: "LEATHB", model: "leathertr", texture: "leathertrchaps" },
        { name: "SUTR1GR", model: "suit1tr", texture: "suit1trgrey" },
        { name: "SUTR1BL", model: "suit1tr", texture: "suit1trblk" },
        { name: "CUTDENM", model: "shorts", texture: "cutoffdenims" },
        { name: "SUITTR1", model: "suit1tr", texture: "suit1trred" },
        { name: "SUITTR2", model: "suit1tr", texture: "suit1trblue" },
        { name: "SUITTR3", model: "suit1tr", texture: "suit1tryellow" },
        { name: "SUTR1GN", model: "suit1tr", texture: "suit1trgreen" },
        { name: "SUTRGNG", model: "suit1tr", texture: "suit1trgang" },
        { name: "LEGS", model: "legs", texture: "player_legs" },
    ],
    camOffset: [0.45, 1.95, 0.2],
    camRotation: [-0.05, 0, -0.2],
};
let shoes: Part = {
    id: 3,
    name: "#FEET",
    items: [
        { name: "COWBOT2", model: "biker", texture: "cowboyboot2" },
        { name: "BASKBO1", model: "bask1", texture: "bask2semi" },
        { name: "BASKBO2", model: "bask1", texture: "bask1eris" },
        { name: "SNKBGAN", model: "sneaker", texture: "sneakerbincgang" },
        { name: "SNKBBLU", model: "sneaker", texture: "sneakerbincblu" },
        { name: "SNKBBLK", model: "sneaker", texture: "sneakerbincblk" },
        { name: "SANDIL1", model: "flipflop", texture: "sandal" },
        { name: "SANDIL2", model: "flipflop", texture: "sandalsock" },
        { name: "SANDIL3", model: "flipflop", texture: "flipflop" },
        { name: "HITOP", model: "bask1", texture: "hitop" },
        { name: "CHUBLK", model: "conv", texture: "convproblk" },
        { name: "CONBLUE", model: "conv", texture: "convproblu" },
        { name: "CONGREN", model: "conv", texture: "convprogrn" },
        { name: "PROTRA1", model: "sneaker", texture: "sneakerprored" },
        { name: "PROTRA2", model: "sneaker", texture: "sneakerproblu" },
        { name: "PROTRA3", model: "sneaker", texture: "sneakerprowht" },
        { name: "PROWHT1", model: "bask1", texture: "bask1prowht" },
        { name: "PROBLK1", model: "bask1", texture: "bask1problk" },
        { name: "BOXSHO1", model: "biker", texture: "boxingshoe" },
        { name: "COHEAT1", model: "conv", texture: "convheatblk" },
        { name: "COHEAT2", model: "conv", texture: "convheatred" },
        { name: "COHEAT3", model: "conv", texture: "convheatorn" },
        { name: "SNHEAT1", model: "sneaker", texture: "sneakerheatwht" },
        { name: "SNHEAT2", model: "sneaker", texture: "sneakerheatgry" },
        { name: "SNHEAT3", model: "sneaker", texture: "sneakerheatblk" },
        { name: "BSHEAT1", model: "bask1", texture: "bask2heatwht" },
        { name: "BSHEAT2", model: "bask1", texture: "bask2heatband" },
        { name: "TIMBER1", model: "bask1", texture: "timbergrey" },
        { name: "TIMBER2", model: "bask1", texture: "timberred" },
        { name: "TIMBER3", model: "bask1", texture: "timberfawn" },
        { name: "TIMBER4", model: "bask1", texture: "timberhike" },
        { name: "COWBOY", model: "biker", texture: "cowboyboot" },
        { name: "BIKEBOT", model: "biker", texture: "biker" },
        { name: "SNAKESN", model: "biker", texture: "snakeskin" },
        { name: "SHOEDR1", model: "shoe", texture: "shoedressblk" },
        { name: "SHOEDR2", model: "shoe", texture: "shoedressbrn" },
        { name: "SHOEDR3", model: "shoe", texture: "shoespatz" },
        { name: "REMCLT", model: "feet", texture: "foot" },
    ],
    camOffset: [-0.25, 1.2, -0.25],
    camRotation: [0, -0.15, -0.9],
};
let chains: Part = {
    id: 13,
    name: "#CHAINS",
    items: [
        { name: "DOGTAG", model: "neck", texture: "dogtag" },
        { name: "NECKAFR", model: "neck", texture: "neckafrica" },
        { name: "STOPWAT", model: "neck", texture: "stopwatch" },
        { name: "NECKSNT", model: "neck", texture: "necksaints" },
        { name: "NECKHA", model: "neck", texture: "neckhash" },
        { name: "NECKCU1", model: "neck2", texture: "necksilver" },
        { name: "NECKCU2", model: "neck2", texture: "neckgold" },
        { name: "NECKRP1", model: "neck2", texture: "neckropes" },
        { name: "NECKRP2", model: "neck2", texture: "neckropeg" },
        { name: "NECKLS", model: "neck", texture: "neckls" },
        { name: "NECKDL", model: "neck", texture: "neckdollar" },
        { name: "NECKCR", model: "neck", texture: "neckcross" },
        { name: "REMCLT", model: undefined, texture: undefined },
    ],
    camOffset: [0.1, 0.75, 0.35],
    camRotation: [0, 0.15, 0.4],
};
let watches: Part = {
    id: 14,
    name: "#WATCHES",
    items: [
        { name: "WATCH7", model: "watch", texture: "watchpink" },
        { name: "WATCH8", model: "watch", texture: "watchyellow" },
        { name: "WATCH3", model: "watch", texture: "watchpro" },
        { name: "WATCH4", model: "watch", texture: "watchpro2" },
        { name: "WATCH9", model: "watch", texture: "watchsub1" },
        { name: "WATCH10", model: "watch", texture: "watchsub2" },
        { name: "WATCH11", model: "watch", texture: "watchzip1" },
        { name: "WATCH12", model: "watch", texture: "watchzip2" },
        { name: "WATCH2", model: "watch", texture: "watchgno" },
        { name: "WATCH5", model: "watch", texture: "watchgno2" },
        { name: "WATCH1", model: "watch", texture: "watchcro" },
        { name: "WATCH6", model: "watch", texture: "watchcro2" },
        { name: "REMCLT", model: undefined, texture: undefined },
    ],
    camOffset: [-0.65, 0.25, 0.1],
    camRotation: [0.05, -0.1, -0.15],
};
let glasses: Part = {
    id: 15,
    name: "#SHADES",
    items: [
        { name: "GROUCH1", model: "grouchos", texture: "groucho" },
        { name: "ZORRO", model: "zorromask", texture: "zorro" },
        { name: "EYEPCH", model: "eyepatch", texture: "eyepatch" },
        { name: "GLASS1", model: "glasses01", texture: "glasses01" },
        { name: "GLASS4", model: "glasses04", texture: "glasses04" },
        { name: "BANDA15", model: "bandmask", texture: "bandred3" },
        { name: "BANDA16", model: "bandmask", texture: "bandblue3" },
        { name: "BANDA17", model: "bandmask", texture: "bandgang3" },
        { name: "BANDA18", model: "bandmask", texture: "bandblack3" },
        { name: "GLASS5", model: "glasses01", texture: "glasses01dark" },
        { name: "GLASS6", model: "glasses04", texture: "glasses04dark" },
        { name: "GLASS3", model: "glasses03", texture: "glasses03" },
        { name: "GLASS8", model: "glasses03", texture: "glasses03red" },
        { name: "GLASS9", model: "glasses03", texture: "glasses03blue" },
        { name: "GLASS7", model: "glasses03", texture: "glasses03dark" },
        { name: "GLASS10", model: "glasses03", texture: "glasses05dark" },
        { name: "GLASS11", model: "glasses03", texture: "glasses05" },
        { name: "REMCLT", model: undefined, texture: undefined },
    ],
    camOffset: [0.1, 0.6, 0.6],
    camRotation: [0, 0.1, 0.7],
};
let hats: Part = {
    id: 16,
    name: "#HATS",
    items: [
        { name: "BANDAN7", model: "bandana", texture: "bandred" },
        { name: "BANDAN8", model: "bandana", texture: "bandblue" },
        { name: "BANDAN9", model: "bandana", texture: "bandgang" },
        { name: "BANDA10", model: "bandana", texture: "bandblack" },
        { name: "BANDA11", model: "bandknots", texture: "bandred2" },
        { name: "BANDA12", model: "bandknots", texture: "bandblue2" },
        { name: "BANDA13", model: "bandknots", texture: "bandblack2" },
        { name: "BANDA14", model: "bandknots", texture: "bandgang2" },
        { name: "CAP25", model: "capknit", texture: "capknitgrn" },
        { name: "CAP26", model: "captruck", texture: "captruck" },
        { name: "CAP28", model: "cowboy", texture: "cowboy" },
        { name: "CAP29", model: "cowboy", texture: "hattiger" },
        { name: "CAP27", model: "helmet", texture: "helmet" },
        { name: "CAP30", model: "moto", texture: "moto" },
        { name: "CAP15", model: "boxingcap", texture: "boxingcap" },
        { name: "CAP16", model: "hockeymask", texture: "hockey" },
        { name: "CAP31", model: "cap", texture: "capgang" },
        { name: "CAP32", model: "capback", texture: "capgangback" },
        { name: "CAP33", model: "capside", texture: "capgangside" },
        { name: "CAP34", model: "capovereye", texture: "capgangover" },
        { name: "CAP35", model: "caprimup", texture: "capgangup" },
        { name: "CAP56", model: "bikerhelmet", texture: "bikerhelmet" },
        { name: "CAP36", model: "cap", texture: "capred" },
        { name: "CAP37", model: "capback", texture: "capredback" },
        { name: "CAP38", model: "capside", texture: "capredside" },
        { name: "CAP39", model: "capovereye", texture: "capredover" },
        { name: "CAP40", model: "caprimup", texture: "capredup" },
        { name: "CAP41", model: "cap", texture: "capblue" },
        { name: "CAP42", model: "capback", texture: "capblueback" },
        { name: "CAP43", model: "capside", texture: "capblueside" },
        { name: "CAP44", model: "capovereye", texture: "capblueover" },
        { name: "CAP45", model: "caprimup", texture: "capblueup" },
        { name: "CAP57", model: "skullycap", texture: "skullyblk" },
        { name: "CAP58", model: "skullycap", texture: "skullygrn" },
        { name: "MANCBLK", model: "hatmanc", texture: "hatmancblk" },
        { name: "MANCPLD", model: "hatmanc", texture: "hatmancplaid" },
        { name: "CAP46", model: "cap", texture: "capzip" },
        { name: "CAP47", model: "capback", texture: "capzipback" },
        { name: "CAP48", model: "capside", texture: "capzipside" },
        { name: "CAP49", model: "capovereye", texture: "capzipover" },
        { name: "CAP50", model: "caprimup", texture: "capzipup" },
        { name: "CAP17", model: "beret", texture: "beretred" },
        { name: "CAP18", model: "beret", texture: "beretblk" },
        { name: "CAP51", model: "cap", texture: "capblk" },
        { name: "CAP52", model: "capback", texture: "capblkback" },
        { name: "CAP53", model: "capside", texture: "capblkside" },
        { name: "CAP54", model: "capovereye", texture: "capblkover" },
        { name: "CAP55", model: "caprimup", texture: "capblkup" },
        { name: "TRIBY1", model: "trilby", texture: "trilbydrk" },
        { name: "TRIBY2", model: "trilby", texture: "trilbylght" },
        { name: "BOWLER1", model: "bowler", texture: "bowler" },
        { name: "BOWLER2", model: "bowler", texture: "bowlerred" },
        { name: "BOWLER3", model: "bowler", texture: "bowlerblue" },
        { name: "BOWLER4", model: "bowler", texture: "bowleryellow" },
        { name: "BOATHA1", model: "boater", texture: "boater" },
        { name: "BOWLER5", model: "bowler", texture: "bowlergang" },
        { name: "BOATHA2", model: "boater", texture: "boaterblk" },
        { name: "REMCLT", model: undefined, texture: undefined },
    ],
    camOffset: [-0.25, 0.75, 0.8],
    camRotation: [0, 0.1, 0.7],
};
let special: Part = {
    id: 17,
    name: "#SHOP7",
    items: [
        { name: "GIMP", model: "gimpleg", texture: "gimpleg" },
        { name: "VALETU", model: "valet", texture: "valet" },
        { name: "COUNTRY", model: "countrytr", texture: "countrytr" },
        { name: "CROUP", model: "valet", texture: "croupier" },
        { name: "POLICE", model: "policetr", texture: "policetr" },
        { name: "BALACLA", model: "balaclava", texture: "balaclava" },
        { name: "PIMPSUT", model: "pimptr", texture: "pimptr" },
        { name: "RDRIVER", model: "garagetr", texture: "garageleg" },
        { name: "PAMEDIC", model: "medictr", texture: "medictr" },
        { name: "REMCLT", model: undefined, texture: undefined },
    ],
    camOffset: [-0.5, 3.3, 0.9],
    camRotation: [0, 0, 0.3],
};

// Haircuts
let haircut: Part = {
    id: 1,
    name: "#HAIRSTY",
    items: [
        { name: "HEAD", model: "head", texture: "player_face" },
        { name: "BLHAIR", model: "head", texture: "hairblond" },
        { name: "REDHAIR", model: "head", texture: "hairred" },
        { name: "BLUHAIR", model: "head", texture: "hairblue" },
        { name: "GRNHAIR", model: "head", texture: "hairgreen" },
        { name: "PNKHAIR", model: "head", texture: "hairpink" },
        { name: "BALD", model: "head", texture: "bald" },
        { name: "BLADBEA", model: "head", texture: "baldbeard" },
        { name: "BALDTSH", model: "head", texture: "baldtash" },
        { name: "BALDGOT", model: "head", texture: "baldgoatee" },
        { name: "HIGHFAD", model: "head", texture: "highfade" },
        { name: "AFROHI", model: "highafro", texture: "highafro" },
        { name: "WEDGE", model: "wedge", texture: "wedge" },
        { name: "SLOPE", model: "slope", texture: "slope" },
        { name: "JHERI", model: "jheri", texture: "jhericurl" },
        { name: "CORNROW", model: "cornrows", texture: "cornrows" },
        { name: "CORNRO2", model: "cornrows", texture: "cornrowsb" },
        { name: "TRAMLIN", model: "tramline", texture: "tramline" },
        { name: "GROOVE", model: "groovecut", texture: "groovecut" },
        { name: "MOHAWK", model: "mohawk", texture: "mohawk" },
        { name: "MOHAWKB", model: "mohawk", texture: "mohawkblond" },
        { name: "MOHAWKP", model: "mohawk", texture: "mohawkpink" },
        { name: "MOHAKBE", model: "mohawk", texture: "mohawkbeard" },
        { name: "AFRO", model: "afro", texture: "afro" },
        { name: "AFROT", model: "afro", texture: "afrotash" },
        { name: "AFROB", model: "afro", texture: "afrobeard" },
        { name: "AFROBL", model: "afro", texture: "afroblond" },
        { name: "AFROFL", model: "flattop", texture: "flattop" },
        { name: "ELVISHA", model: "elvishair", texture: "elvishair" },
        { name: "BEARD", model: "head", texture: "beard" },
        { name: "TASH", model: "head", texture: "tash" },
        { name: "GOATEE", model: "head", texture: "goatee" },
        { name: "AFROGOT", model: "afro", texture: "afrogoatee" },
    ],
    clearBodyPart: [16, 17],
    camOffset: [-0.3, 0.75, 0.75],
    camRotation: [0.1, -0.2, 0.75],
};

// Tattoos
let leftUpperArm: Part = {
    id: 4,
    name: "#LARMTP",
    items: [
        { name: "4WEED", model: "4WEED", texture: "4weed" },
        { name: "4RIP", model: "4RIP", texture: "4rip" },
        { name: "4SPIDER", model: "4SPIDER", texture: "4spider" },
        { name: "REMCLT", model: undefined, texture: undefined },
    ],
    clearBodyPart: [0, 17],
    camOffset: [-0.75, 0.05, 0.5],
    camRotation: [0, -0.05, 0.45],
};
let leftLowerArm: Part = {
    id: 5,
    name: "#LARMLW",
    items: [
        { name: "5GUN", model: "5GUN", texture: "5gun" },
        { name: "5CROSS", model: "5CROSS", texture: "5cross" },
        { name: "5CROSS2", model: "5CROSS2", texture: "5cross2" },
        { name: "5CROSS3", model: "5CROSS3", texture: "5cross3" },
        { name: "REMCLT", model: undefined, texture: undefined },
    ],
    clearBodyPart: [0, 17],
    camOffset: [-0.85, 0.1, 0.35],
    camRotation: [0, 0, 0],
};
let rightUpperArm: Part = {
    id: 6,
    name: "#RARMTP",
    items: [
        { name: "6AZTEC", model: "6AZTEC", texture: "6aztec" },
        { name: "6CROWN", model: "6CROWN", texture: "6crown" },
        { name: "6CLOWN", model: "6CLOWN", texture: "6clown" },
        { name: "6AFRICA", model: "6AFRICA", texture: "6africa" },
        { name: "REMCLT", model: undefined, texture: undefined },
    ],
    clearBodyPart: [0, 17],
    camOffset: [0.75, 0.05, 0.5],
    camRotation: [0, -0.05, 0.45],
};
let rightLowerArm: Part = {
    id: 7,
    name: "#RARMLW",
    items: [
        { name: "7CROSS", model: "7CROSS", texture: "7cross" },
        { name: "7CROSS2", model: "7CROSS2", texture: "7cross2" },
        { name: "7CROSS3", model: "7CROSS3", texture: "7cross3" },
        { name: "7MARY", model: "7MARY", texture: "7mary" },
        { name: "REMCLT", model: undefined, texture: undefined },
    ],
    clearBodyPart: [0, 17],
    camOffset: [0.85, 0.1, 0.35],
    camRotation: [0, 0, 0],
};
let leftChest: Part = {
    id: 9,
    name: "#LCHEST",
    items: [
        { name: "9CROWN", model: "9CROWN", texture: "9crown" },
        { name: "9GUN", model: "9GUN", texture: "9gun" },
        { name: "9GUN2", model: "9GUN2", texture: "9gun2" },
        { name: "9HOMBY", model: "9HOMBY", texture: "9homeboy" },
        { name: "9BULLT", model: "9BULLT", texture: "9bullet" },
        { name: "9RASTA", model: "9RASTA", texture: "9rasta" },
        { name: "REMCLT", model: undefined, texture: undefined },
    ],
    clearBodyPart: [0, 17],
    camOffset: [-0.15, 0.75, 0.5],
    camRotation: [-0.05, 0, 0.5],
};
let rightChest: Part = {
    id: 10,
    name: "#RCHEST",
    items: [
        { name: "10LS", model: "10LS", texture: "10ls" },
        { name: "10LS2", model: "10LS2", texture: "10ls2" },
        { name: "10LS3", model: "10LS3", texture: "10ls3" },
        { name: "10LS4", model: "10LS4", texture: "10ls4" },
        { name: "10LS5", model: "10LS5", texture: "10ls5" },
        { name: "10OG", model: "10OG", texture: "10og" },
        { name: "10WEED", model: "10WEED", texture: "10weed" },
        { name: "REMCLT", model: undefined, texture: undefined },
    ],
    clearBodyPart: [0, 17],
    camOffset: [0.15, 0.75, 0.5],
    camRotation: [0.05, 0, 0.5],
};
let stomach: Part = {
    id: 11,
    name: "#BELLY",
    items: [
        { name: "11GROVE", model: "11GROVE", texture: "11grove" },
        { name: "11GROV2", model: "11GROV2", texture: "11grove2" },
        { name: "11GROV3", model: "11GROV3", texture: "11grove3" },
        { name: "11DICE", model: "11DICE", texture: "11dice" },
        { name: "11DICE2", model: "11DICE2", texture: "11dice2" },
        { name: "11JAIL", model: "11JAIL", texture: "11jail" },
        { name: "11GGIFT", model: "11GGIFT", texture: "11godsgift" },
        { name: "REMCLT", model: undefined, texture: undefined },
    ],
    clearBodyPart: [0, 17],
    camOffset: [0, 0.75, 0.25],
    camRotation: [0, 0, 0.3],
};
let back: Part = {
    id: 8,
    name: "#BACK",
    items: [
        { name: "8SA", model: "8SA", texture: "8sa" },
        { name: "8SA2", model: "8SA2", texture: "8sa2" },
        { name: "8SA3", model: "8SA3", texture: "8sa3" },
        { name: "8WESTSD", model: "8WESTSD", texture: "8westside" },
        { name: "8SANTOS", model: "8SANTOS", texture: "8santos" },
        { name: "8POKER", model: "8POKER", texture: "8poker" },
        { name: "8GUN", model: "8GUN", texture: "8gun" },
        { name: "REMCLT", model: undefined, texture: undefined },
    ],
    clearBodyPart: [0, 17],
    camOffset: [0, -0.75, 0.6],
    camRotation: [0, 0, 0.5],
};
let lowerBack: Part = {
    id: 12,
    name: "#LBACK",
    items: [
        { name: "12ANGEL", model: "12ANGEL", texture: "12angels" },
        { name: "12MAYBR", model: "12MAYBR", texture: "12mayabird" },
        { name: "12DAGER", model: "12DAGER", texture: "12dagger" },
        { name: "12BNDIT", model: "12BNDIT", texture: "12bandit" },
        { name: "12CROSS", model: "12CROSS", texture: "12cross7" },
        { name: "12MYFAC", model: "12MYFAC", texture: "12mayaface" },
        { name: "REMCLT", model: undefined, texture: undefined },
    ],
    clearBodyPart: [0, 17],
    camOffset: [0, -0.75, 0.25],
    camRotation: [0, 0, 0.3],
};

let body: Part[] = [
    torso,
    legs,
    shoes,
    chains,
    watches,
    glasses,
    hats,
    special,
    haircut,
    leftUpperArm,
    leftLowerArm,
    rightUpperArm,
    rightLowerArm,
    leftChest,
    rightChest,
    stomach,
    back,
    lowerBack,
];

// Generate body parts' menus
body.forEach((p) => {
    p.menu = new AltMenu(
        p.name,
        p.items.map((i) => ({
            name: `#${i.name}`,
            enter: function () {
                if (i.model !== undefined && i.texture !== undefined) {
                    plr.giveClothesOutsideShop(i.texture, i.model, p.id);
                } else {
                    plr.giveClothes(0, 0, p.id);
                }
                plr.buildModel();
            },
        })),
        {
            disableHud: true,
            selectedBackgroundColour: [0, 0, 90, 127],
            showCounter: true,
        },
    );
});

// General menu
export let appearanceMenu: AltMenu = new AltMenu(
    "Appearance",
    body.map((p) => ({
        name: p.name,
        enter: function () {
            Camera.AttachToChar(plc, ...p.camOffset, ...p.camRotation, 0, 2);
        },
        click: function () {
            if (p.clearBodyPart) {
                p.clearBodyPart.forEach((p) => plr.giveClothes(0, 0, p));
                plr.buildModel();
            }
            while (p.menu.isDisplayed()) {
                wait(0);
            }
        },
    })),
    {
        selectedBackgroundColour: [0, 70, 0, 150],
        showCounter: true,
    },
);
